blueprint:
  name: Play media (timed) from Music Assistant
  description: Starts a timer with the given amount of time. Needs automation to check for timer finished
  domain: script
  input:
    player:
      name: Media player
      selector:
        entity:
          filter:
            domain: media_player
    media:
      name: Media string
      selector:
        text:
    volume:
      name: Volume
      selector:
        number:
          min: 0
          max: 1
          step: 0.01
    timer:
      name: Timer
      selector:
        entity:
          filter:
            domain: timer
    amount:
      name: Amount of time
      selector:
        duration:

sequence:
  - action: media_player.media_stop
    metadata: {}
    data: {}
    target:
      entity_id: !input player
  - action: media_player.volume_set
    metadata: {}
    data:
      volume_level: !input volume
    target:
      entity_id: !input player
    enabled: true
  - action: music_assistant.play_media
    metadata: {}
    data:
      media_id: !input media
    target:
      entity_id: !input player
  - action: timer.cancel
    metadata: {}
    data: {}
    target:
      entity_id: !input timer
  - action: timer.start
    metadata: {}
    data:
      duration: !input amount
    target:
      entity_id: !input timer
